### ISSUE TITLE
Does not work reliably (or at all) in Firefox and IE 11

### ISSUE THREAD

**Issue by ColaColin** [cdgugler/shatter.js#14]
Because of this reason: http://stackoverflow.com/questions/4776670/should-setting-an-image-src-to-data-url-be-available-immediately

shatter.js sets the src and expects the image to be ready to use directly afterwards. That's not the case, yielding blank images.

I've not found a quick hack to keep the synchronous way of shatter.js, the only working solution to this seems to be to use callbacks as described in the playing it save part of the stackoverflow post.

**Comment by cdgugler** [comment]
I believe this is also an issue on Safari. #12 
I believe you're right, there doesn't seem to be a good way to get this working synchronously in those browsers.
Need to add a callback.

**Comment by cdgugler** [comment]
Merged a fix into the Dev branch which may fix this. Seems to work in Firefox. Needs tested in IE and Safari.

**Comment by ColaColin** [comment]
That is an interesting solution. Does that work in chrome? They have an issue that makes it seem like it might not: https://bugs.chromium.org/p/chromium/issues/detail?id=330554

**Comment by cdgugler** [comment]
I tested on Chrome and Firefox in Linux and it worked. I think since the clonedNode is just being used a placeholder (to create a new image and reset the src), that bug shouldn't be an issue.
I'll try to test all browsers I have available this weekend.

**Comment by cdgugler** [comment]
Clearing out issues for previous version. Rewrite uses async
