### ISSUE TITLE
examples broken?

### ISSUE THREAD

**Issue by julianeden** [cdgugler/shatter.js#16]
Hi, I was looking to use shatter.js for a project, but I can't tell from the examples on the site if it fits my need. Can you take a look at the site and confirm that the interactive examples are working as expected? When I go to [this page](http://cdgugler.github.io/shatter.js/examples/dom.html), I am unable to type anything in the "number of pieces" input box for unknown reasons-- so I used the dev console to change the input box's value to 1 programmatically and clicked "Create another," but then the page starts glitching and jumping without any other apparent result. Likewise, the Phase Example just links to a black box.

Am I doing something wrong?

Thanks.

**Comment by aerovistae** [comment]
(I am using the most recent version of Chrome on Windows 7 and have no extensions running.)

**Comment by cdgugler** [comment]
The actual image splitting still works in Chrome for me (on Linux) but the example does look broken. It works with on the initial load, but adding additional objects causes the glitching. This probably has more to do with the jGravity plugin in that example.

**Comment by aerovistae** [comment]
Any chance it's going to be fixable? :D

**Comment by aerovistae** [comment]
(Also I don't see anything on the initial load-- is there supposed to be something there beyond the black screen?)

**Comment by cdgugler** [comment]
ahh, yes, eventually! 
I just updated the readme to unmaintained. I've been swamped with other projects.

**Comment by aerovistae** [comment]
Understood, thanks.

**Comment by cdgugler** [comment]
Is this example: http://cdgugler.github.io/shatter.js/examples/dom.html
Blank for you?

**Comment by aerovistae** [comment]
Yes. All black. If I examine it with dev tools I can see there are some img's inside the container which are jiggling around, but they are invisible.

**Comment by cdgugler** [comment]
Interesting. I'll check it out in Windows when I can.

**Comment by cdgugler** [comment]
Samples/Project rewritten
